# Numpy Class

In [8]:
import numpy as np

In [9]:
#Create a 1D array

arr1 = np.array([1, 2, 3, 4])
print("1D Array : ", arr1)

1D Array :  [1 2 3 4]


In [10]:
#Create a 2D array

arr2 = np.array([ [1,2] , [3,4] ])
print("2D array is : ",arr2)

2D array is :  [[1 2]
 [3 4]]


In [11]:
import numpy as np

arr = np.array([ [1,2,3], [4,5,6]])
print("Array : \n" , arr)
print("Shape : " , arr.shape)
print("Dimension : " , arr.ndim)
print("\nData Types : ", arr.dtype)

Array : 
 [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
Dimension :  2

Data Types :  int64


In [13]:
#creating 1D array

arr_1d = np.array([1,2,3,4])
print("Shape is : " , arr_1d.shape)

Shape is :  (4,)


In [15]:
#creating 2d array

arr_2d = np.array([ [1,2,3] , [4,5,6]])
print("2D Array is : \n" ,arr_2d)
print("Shape : " , arr_2d.shape)
print("Dimension is : " , arr_2d.ndim)


2D Array is : 
 [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
Dimension is :  2


In [18]:
#3d Array 
arr_3d = np.array( [[ [1,2] , [5,6] , [7,8] ]])

In [19]:
print("3D array : \n" , arr_3d.shape)

3D array : 
 (1, 3, 2)


# Array Operations

In [20]:
import numpy as np

arr = np.array([1,2,3,4,5])
print("Original array : " , arr)
print("Add 5 : " , arr + 5 ) #esle array ko sabai element ma 5 le add garcha

Original array :  [1 2 3 4 5]
Add 5 :  [ 6  7  8  9 10]


# Array Indexing & Slicing


In [21]:
import numpy as np

arr = np.array([ [1,2,3] , [4,5,6] ])

In [22]:
print("Array : \n", arr)

Array : 
 [[1 2 3]
 [4 5 6]]


In [23]:
print("Element at [0,1]: " , arr[0,1])

Element at [0,1]:  2


In [24]:
print("First Row:" , arr[0, :])

First Row: [1 2 3]


# Mathematical Functions

In [25]:
import numpy as np 

arr = np.array([ 1, 2 , 3  ,4 ])
print("Array : " , arr)

Array :  [1 2 3 4]


In [27]:
print("Sab Element ko Sine nikalcha : " , np.sin(arr))

Sab Element ko Sine nikalcha :  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [28]:
print("Sab Elements ko total nikalna cha bhane : ", np.sum(arr))

Sab Elements ko total nikalna cha bhane :  10


# Reshaping arrays

In [29]:
#array ko dimension interchangeable pani huncha
# i.e 1d lai 2d ma change garna ni milo & 2d lai 1d ma change garna ni milo

In [30]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print("Original : " , arr)
reshaped = arr.reshape(2,3)
print("Reshaped to 2x3 : \n " , reshaped)

Original :  [1 2 3 4 5 6]
Reshaped to 2x3 : 
  [[1 2 3]
 [4 5 6]]


In [31]:
#1D lai 2D ma lada chai 1D ma jati element cha tyo totalElements = row x column in 2d

#thulo dimension lai sano ma lada chai flatten() function use huncha
#or reshape ni use huncha

array_2d = reshaped
array_1d_reshape = array_2d.reshape(6)
print("2D to 1D is : " , array_1d_reshape)

2D to 1D is :  [1 2 3 4 5 6]


In [34]:
#flatten use garera chai
#flatten le chai afaile bujera -> jun sikai dimension ko array lai 
#chai 1d ma convert garcha

array_1d_flatten_use_garera = array_2d.flatten()
print("2D to 1D is : " , array_1d_flatten_use_garera)

2D to 1D is :  [1 2 3 4 5 6]
